#!/opt/mailman3_exporter-0.9/bin/python3
# -*- coding: utf-8 -*-

import sys
import mailman_exporter

if __name__ == '__main__':
    try:
        mailman_exporter.main()
    except KeyboardInterrupt:
        sys.exit(0)
